"""create complaints table

Revision ID: fff63cd7dec5
Revises: 
Create Date: 2026-08-10 18:55:43.666279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff63cd7dec5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_source', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_strength', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('manufacturing_date', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('quantity_affected', sa.String(), nullable=True),
    sa.Column('complaint_type', sa.String(), nullable=True),
    sa.Column('complaint_date', sa.String(), nullable=True),
    sa.Column('complaint_description', sa.Text(), nullable=True),
    sa.Column('initial_severity', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
